### ISSUE TITLE
CAP SKU'S

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#10]
Version 1 of the Intel Education Content Access Point has 4 SKU's

1) Wi-Fi only, i.e. no HDD
2) Wi-Fi plus 500GB HDD
3) Wi-Fi plus 500GB HDD plus 3G 
4) Wi-Fi plus 500GB HDD plus 4G 

The SKU's are not upgradeable. That is you cannot add a HDD in SKU 1) to make it SKU 2. That is because the SKU's are missing the connectors and antennas.

However, it is possible to replace the standard 2'5" HDD with an SDD or a larger HDD. It takes about 5min.
It is also possible to upgrade the 2GB memory module with a 4GB module. Currently 4GB is the maximum of the current chipset.

**Comment by spatiald** [comment]
Information moved to wiki.
