### ISSUE TITLE
[SOLVED] Redirect "Local Content" button to Intel's content site 

### ISSUE THREAD

**Issue by spatiald** [rachelproject/rachelplus#12]
On RACHELplus devices, we would like the "Local Content" link to redirect to Intel's default content site.  So...we change two (2) links within the file /media/RACHEL/rachel/index.php as follows:

Change line 60 and 139 to:
```html
<li><a href="http://192.168.88.1:8090">LOCAL CONTENT</a></li>
```

**Comment by hackersforcharity** [comment]
Updated this post to properly display the line that needs to be replaced.


On Jul 11, 2015, at 15:05, Sam Kinch <notifications@github.com> wrote:

On RACHELplus devices, we would like the "Local Content" link to redirect
to Intel's default content site. So...we change two (2) links within the
file /media/RACHEL/rachel/index.php as follows:

Change line 60 and 139 to:
LOCAL CONTENT <http://192.168.88.1:8090>

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/12>.

**Comment by j-schwartz** [comment]
So I refer the following:

**Comment by spatiald** [comment]
That works perfectly...thanks Jeremy.
