### ISSUE TITLE
Defaults: IP Address, Password, SSID, etc.

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#13]
I would suggest that we settle on a set of default IP addresses, password, SSID, etc.

I would not necessarily use the Intel defaults. Jeremy as the god father of Rachel, can you make recommendations?

Also, please note that while there will be installations where devices connect via the "WAN" connection.

That is, the CAP will be connected to an existing network via the WAN port and gets assigned an IP address. Everything should be accessible via that IP address.

**Comment by j-schwartz** [comment]
Agreed - I'd like to match as closely as possible to RACHEL-Pi

Default ip address: 10.10.10.10
SSID: RACHEL
teacher user: teacher
teacher pass: teacher
admin user: admin
admin pass: Rachel+1

In general I do not secure the SSID, but when I do, I use worldpossible as the password.

When jumping around between ports, I prefer we use the javascript code for navigation.

**Comment by spatiald** [comment]
We may have to rethink the default IP.  Those IPs are "baked into" the
rcConf and rcConfd binaries that the CAP uses. I can't change that at this
moment. If we can get someone from Intel to share the pre-compiled code
with us, than we could easily make those changes.

Also, the setwanip.sh script we used in previous RACHEL builds will solve
changing the eth0 IP when users want to access RACHEL via Ethernet.  I will
ensure that script is on the RACHELplus GitHub.

Sam

On Jul 13, 2015, at 13:52, Jeremy Schwartz <notifications@github.com> wrote:

Agreed - I'd like to match as closely as possible to RACHEL-Pi

Default ip address: 10.10.10.10
SSID: RACHEL
teacher user: teacher
teacher pass: teacher
admin user: admin
admin pass: Rachel+1

In general I do not secure the SSID, but when I do, I use worldpossible as
the password.

When jumping around between ports, I prefer we use the javascript code for
navigation.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/13#issuecomment-121004875>
.

**Comment by j-schwartz** [comment]
Interesting, perhaps that's why I'm having some WiFi connectivity issues as
is.

**Comment by j-schwartz** [comment]
Will setwanip.sh allow dual functionality at the same time?

For instance, our largest use case for these right now is the prison
system.  They currently have a LAN with switch, but no WiFi.  They will be
accessing this device both over desktops connected to the LAN in the
computer center, but also simultaneously with tablets for kids with
behavioral issues that don't allow them to sit at the desktops.  There is
currently no wireless at the facilities.

**Comment by bnordha** [comment]
Sam

do you have any idea why they decided to hard bake into the code?

also, do you know what will not work when the default IP address is changed?

Thanks, Bernd

**Comment by spatiald** [comment]
@j-schwartz Yes, what setwanip.sh does is search /media/RACHEL/rachel/index.php for any IP and changes it to 192.168.88.1 (when only attached to wifi) OR to the WAN IP when there is one assigned.  The reasoning:  the only IPs that are currently in the RACHEL index.php file are needed because alternate port is being referenced.  We wanted the ability for anyone to connect to the CAP when there was a ethernet IP assigned.  

In your prison environment, are the tablets the kids use connected via usb or ethernet cable??  I know you said there is no wireless; I guess that part is a bit confusing to me.

@bnordha The only reason I would do it is to minimize the "damage" another customizer does to the basic functionality of the CAP.  Any script that redirects to http://my.content will not work if the 192.168.88.1 IP is changed.  That IP is hardcoded into both the IP settings and the DNS redirects.

**Comment by j-schwartz** [comment]
Sorry, the tablets are a new addition to a previously LAN only (without
wireless) environment.  Basically, people on desktop computers will be
accessing RACHEL through an assigned IP of the CAP from the switch
(192.168.1.XXX) and people on wireless will be directly connected to the
CAP and navigating to whatever IP address we assign the CAP (10.10.10.10)?

At least, this is how I understand the desired setup.

**Comment by bnordha** [comment]
Yes, that is a common setup, and I have had no issues with it, though I haven’t done a full stress test on it.

**Comment by spatiald** [comment]
Unless we have a way to change the pre-compiled code, I don’t think its wise to change to the RACHEL standard 10.10.10.10. At least for the current CAP builds.  If we can find a way to modify the hard-coded IPs in the future.

That’s my opinion but I will leave the decision up to Jeremy.

**Comment by spatiald** [comment]
What about KA Lite?  Are we using rachel:rachel or admin:Rachel+1 for the admin login?

Default ip address: 192.168.88.1 (builtin redirect from 10.10.10.10 to 192.168.88.1 when connected via wifi)
SSID: RACHEL
teacher user: teacher
teacher pass: teacher
admin user: admin
admin pass: Rachel+1

**Comment by j-schwartz** [comment]
We're currently setting it up as rachel:rachel but now that you bring it
up, teacher:teacher probably makes more sense to match what we do for the
Intel stuff.

**Comment by hackersforcharity** [comment]
Okay, that makes sense. Will do that from here out.

On Aug 1, 2015, at 19:19, Jeremy Schwartz <notifications@github.com> wrote:

We're currently setting it up as rachel:rachel but now that you bring it
up, teacher:teacher probably makes more sense to match what we do for the
Intel stuff.

On Sat, Aug 1, 2015 at 6:55 AM Sam Kinch <notifications@github.com> wrote:

> What about KA Lite? Are we using rachel:rachel or admin:Rachel+1 for the
> admin login?
>
> Default ip address: 192.168.88.1 (builtin redirect from 10.10.10.10 to
> 192.168.88.1 when connected via wifi)
>
>
> SSID: RACHEL
> teacher user: teacher
> teacher pass: teacher
> admin user: admin
> admin pass: Rachel+1
>
> —
>
>
> Reply to this email directly or view it on GitHub
> <
https://github.com/rachelproject/rachelplus/issues/13#issuecomment-126917213
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/13#issuecomment-126961355>
.

**Comment by click2tman** [comment]
I am connected to WIFI but no redirect. When I try to access my.content or 192.168.88.1, nothing happens. Any idea why? How to I stop and start all services running on the device? I simply shutdown the device and after starting again, the above happen. What web server is installed? Apache or NGNIX?

**Comment by spatiald** [comment]
That is usually indicative of a hard drive failing to mount or you upgraded the CAP’s firmware manually (using the build in firmware upgrade tool) and didn’t repair the installation afterward (we recommend to that you only upgrade the firmware using our RACHEL USB drive).

The web server is lighttpd

For troubleshooting, the best thing to check is the log files.  You will have to log in via SSH to view them.  On Windows, use putty.

While connected to the CAP’s wireless, SSH to 192.168.88.1.  The user “root” and the password “123lkj"

First, one that will indicate if the startup script “rachel-scripts.sh” ran successfully.  The log file is:
/var/log/RACHEL/rachel-scripts.log

Second, type in:
df -h

You should something like here:

root@WRTD-303N-Server:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mmcblk0p4  5.3G  3.2G  1.9G  64% /
udev            943M   12K  943M   1% /dev
tmpfs           383M  472K  382M   1% /run
none            5.0M     0  5.0M   0% /run/lock
none            956M     0  956M   0% /run/shm
/dev/mmcblk0p3  181M  102M   71M  60% /boot
/dev/mmcblk0p5  992M  1.3M  940M   1% /recovery
/dev/sda1        20G   44M   19G   1% /media/preloaded
/dev/sda2        99G   61M   94G   1% /media/uploaded
/dev/sda3       339G  217G  105G  68% /media/RACHEL
/dev/mmcblk0p2   94M   76M   19M  81% /boot/efi

If you don’t see the /media/RACHEL in the list, than the hard drive didn’t mount during boot.  If that is the case, run “dmesg” and see if there are any errors for /dev/sda during boot.

sam
