### ISSUE TITLE
Battery script doesn't save status after power failure

### ISSUE THREAD

**Issue by spatiald** [rachelproject/rachelplus#14]
Script tracks duration just fine while running.  If you check the duration-results.log file it shows all the appropriate lines:
```
root@WRTD-303N-Server:~# cat duration-results
[+] Battery Duration Test Script - Version 7
[+] Test Started:  Thu Jul 16 15:00:44 EDT 2015
[-] Power failure:  Thu Jul 16 15:00:49 EDT 2015
[!] Battery lasted:  0 hours, 0 minutes, 5 seconds
```
However, once power fails, you get:
```
root@WRTD-303N-Server:~# cat duration-results
[+] Battery Duration Test Script - Version 7
[+] Test Started:  Wed Jul 15 13:52:10 EDT 2015
```

I believe it's because of the while loop and the way the CAP shuts down. 

More testing needed...

**Comment by spatiald** [comment]
Just after I wrote this issue, I thought of an idea and it worked.  LOL

The battery script "while loop" was getting killed on shutdown; however, it was in a clean way that prevented it from writing it's last update to the device under test.  I rewrote the script so the "while loop" posts its current data to a temp file and, every 5 seconds, updates the duration-results.log file.

**Comment by spatiald** [comment]
Crap...still not working.  It seems to work sporadically but not reliably.  I wish I could reliably replicate without waiting for battery to die.  Not good to continually do to a LiPo.

**Comment by spatiald** [comment]
Okay, I think its fixed now.  Please test if you get a chance.
```bash
sudo wget https://github.com/rachelproject/rachelplus/raw/master/battery-test.sh -O /root/battery-test.sh; bash battery-test.sh
```

**Comment by j-schwartz** [comment]
Sam - is this normal?

2015-07-17 22:06:56 (205 MB/s) - `/root/battery-test.sh' saved [3987/3987]

battery-test.sh: line 20: syntax error near unexpected token `('
battery-test.sh: line 20: `VERSION=2 (July 17, 2015) #script version'

I'm going to test with 3 client devices using HTTrack to re scrape RACHEL.
Should mimic a fairly heavy workload.

**Comment by spatiald** [comment]
ha that’s funny…last minute change to add a date failed me…sorry about that, one sec
/s

**Comment by spatiald** [comment]
Should be fixed...I uploaded the new one as Version 3

**Comment by bnordha** [comment]
there is a file called /tmp/batteryStatus which apparently records the battery status and is continuously updated.

**Comment by spatiald** [comment]
@bnordha True, /tmp/batteryStatus does show the current status but this bug references the batter duration script which will determine how long the device runs on battery before dying.

Script works now and I think this issue is resolved; reopen if needed.
