### ISSUE TITLE
Requests for Enhancements

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#16]
Everybody,

I am collected input on requests for Enhancements to give to Intel. Thus, can you please add features/improvements that you would like to see in the CAP? These are features that Intel controls, i.e. hardware & OS/firmware related.

**Comment by spatiald** [comment]
Need info from builder on serial port connection.

Is there one?  Is it the micro-USB?  I haven't tested that yet but it seems likely.
If there is not one...it needs one.

**Comment by edresor** [comment]
Sorry.  I was trying to close my comment box.

**Comment by spatiald** [comment]
Three big requests in order of priority (my opinion):

1.  IP rating for dust and water resistance (IP52-58 or IP62-68 minimum)
2.  3G/LTE card slot on devices by default 
3.  SSD drive (cost is our limiting factor...500GB is around USD $230)

**Comment by spatiald** [comment]
- 2GB memory
- 64 bit OS and EFI

**Comment by spatiald** [comment]
Add the ability to switch the Ethernet port from WAN uplink mode (current) to LAN mode so that you can plug physical computers into it and they get dhcp addresses.

**Comment by needlestack** [comment]
With the CAP 2.0 coming out in a couple months - how did Intel do?

**Comment by spatiald** [comment]
Based on their announcement info (below), amazing.  The only enhancement I
would love to see is the ability to add a dust cover to the open ports, a
rubber gasket for the covers, and water-proof (or at least resistant
buttons).  The button/gasket could be built into the production with the
dust cover as an optional item.  For off the grid, rural areas, I think
these additions would solidify it's market.

OS
Ubuntu* 14.04 LTS 64-bit

Connectivity options
IEEE 802.11 b/g/n (2.4GHz) or IEEE 802.11 a/n/ac (5GHz)
Wired gigabit Ethernet WAN
Optional 3G, optional LTE

Processor
Intel® Atom™ processor E3826 dual-core, 1.46GHz

Memory
4GB 64-bit DDR3L-1067

Storage
16GB eMMC, optional 500GB SATA HDD
Support for external USB HDD

Battery
1 Lithium-ion polymer 7.4v, 4050mAh (up to 4.75 hours of battery life)

System I/O
1x standard USB 3.0 (USB 2.0 compatible)
1x RJ45, DC-in

Power supply
AC input: 100–240V
DC output: 12V/2A
Frequency: 50–60Hz, single phase

LED indicators
1x system LED, 1x 3G/LTE LED

Buttons
1x power button, 1x factory reset button

**Comment by needlestack** [comment]
That sounds pretty great. I hope gemtek delivers a quality build :)
