### ISSUE TITLE
KA-Lite Administrator Account

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#2]
KA-Lite install is not creating an administrator account

**Comment by j-schwartz** [comment]
Successfully fixed this yesterday, but I'm not exactly remembering how.  I believe I did ./root/ka-lite/kalite/manage.py ---createsuperuser

**Comment by edresor** [comment]
I used the following command from the /bin folder in the /ka-lite folder.  There about 117  optional commands which are listed according to type of function in []'s.  The two commands for authorization are below.

cap@WRTD-303N-Server:~/ka-lite/bin$ sudo python kalite manage -h

[auth]
    changepassword
    createsuperuser

**Comment by spatiald** [comment]
Reopen if needed.
