### ISSUE TITLE
Naming RACHEL log file with colon

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#21]
I'm not sure where I can change it, but naming the log file with date - time is great, however windows can't read or save files with a colon (:) in the file name.  Can we get the time to save to the file name without a colon?

**Comment by spatiald** [comment]
Good catch - fixed in commit 5f56d55239997628e7fe58408d7ae41ad8b27108

**Comment by j-schwartz** [comment]
Post-install log has a colon also

**Comment by spatiald** [comment]
Thanks, fixed that as well...it will be pushed when I push some other updates I am working on with that script.  Probably tonight.
