### ISSUE TITLE
Re-run KA-Lite Setup to Allow for WAN Sync

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#23]
Devices shipped out by us will be pre-registered for plug-n-play use of KA-Lite offline.  If a deployment scenario does have internet, we need to wipe that pre-registration and re-register with KA-Lite global.  Can we put a clean script in to do the following (as suggested by Jamie at FLE):

For re-running setup, if you let me know what path KA Lite is installed to, I can provide more specific instructions. If we assume it's /home/pi/ka-lite/, the command would be something like:
rm /home/pi/ka-lite/kalite/database/data.sqlite; /home/pi/ka-lite/kalite/manage.py setup

An even better option, assuming you're running version 0.13.x (very recommended) would be to have the following be done before creating future images (this would be done on the device being used to create the image, before cloning):
Stop the KA Lite server (something like /home/pi/ka-lite/scripts/stop.sh, or sudo service ka-lite stop, depending on how it's set up)
Run the following to delete the Device ID and crypto keys from the database (without affecting the admin user you have already set up): /home/pi/ka-lite/kalite/manage.py runcode "from django.conf import settings; settings.DEBUG_ALLOW_DELETIONS = True; from securesync.models import Device; Device.objects.all().delete(); from fle_utils.config.models import Settings; Settings.objects.all().delete()"
Shutdown the Pi and clone the image without rebooting again. Then, when the cloned image is next booted and KA Lite starts, it will automatically create a new Device ID and crypto keypair.
(Let me know if you have any questions with that process; it would be hugely valuable in ensuring that Rachel users would have the option to set up syncing.)

We'll also be releasing version 0.14 in a couple of weeks, with lots of new goodies, and hopefully soon a Debian installer for the Pi.

**Comment by spatiald** [comment]
So the Dev build of the configure script (in testing folder) has a sanitize
option under the Utilities menu. It will prep the CAP by sanitizing the
current configure info. I am still trying to figure out if it's possible to
pre-register it from the command line.



On Jul 28, 2015, at 11:48, Jeremy Schwartz <notifications@github.com> wrote:

Devices shipped out by us will be pre-registered for plug-n-play use of
KA-Lite offline. If a deployment scenario does have internet, we need to
wipe that pre-registration and re-register with KA-Lite global. Can we put
a clean script in to do the following (as suggested by Jamie at FLE):

For re-running setup, if you let me know what path KA Lite is installed to,
I can provide more specific instructions. If we assume it's
/home/pi/ka-lite/, the command would be something like:
rm /home/pi/ka-lite/kalite/database/data.sqlite;
/home/pi/ka-lite/kalite/manage.py setup

An even better option, assuming you're running version 0.13.x (very
recommended) would be to have the following be done before creating future
images (this would be done on the device being used to create the image,
before cloning):
Stop the KA Lite server (something like /home/pi/ka-lite/scripts/stop.sh,
or sudo service ka-lite stop, depending on how it's set up)
Run the following to delete the Device ID and crypto keys from the database
(without affecting the admin user you have already set up):
/home/pi/ka-lite/kalite/manage.py runcode "from django.conf import
settings; settings.DEBUG_ALLOW_DELETIONS = True; from securesync.models
import Device; Device.objects.all().delete(); from fle_utils.config.models
import Settings; Settings.objects.all().delete()"
Shutdown the Pi and clone the image without rebooting again. Then, when the
cloned image is next booted and KA Lite starts, it will automatically
create a new Device ID and crypto keypair.
(Let me know if you have any questions with that process; it would be
hugely valuable in ensuring that Rachel users would have the option to set
up syncing.)

We'll also be releasing version 0.14 in a couple of weeks, with lots of new
goodies, and hopefully soon a Debian installer for the Pi.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/23>.

**Comment by spatiald** [comment]
Sanitize function in place...interactive mode, option 8, option 11.
