### ISSUE TITLE
KA-Lite Install

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#24]
I think it'd be good to have some options to "go back" during some of the installation processee.

For instance, when reinstalling KA-Lite up upgrading it, if we've already downloaded the assessment items package and placed it appropriately, the script asks for the filename.  To me at least, I know the stuff is in the right place, and I'm not sure what filename that is.  I get stuck in a never ending loop.

Also, in another place, if I choose not to download ka-lite_content.zip, it asks if I have downloaded it elsewhere.  I have, but I've also unpacked it elsewhere as the CAP is slow to unpack it.  If I say yes at that prompt, I get stuck, because I don't have the zip file anywhere nor do I want to do the unpacking.

Perhaps a "skip" or "go back" option could be enabled?

**Comment by bnordha** [comment]
Jeremy

 

You raise a good point, but I think it brings up a fundamental question. How do you see the install script being used? Is it is just for internal purposes, and the main install is done through the USB recovery method?


Then second, for things like Ka-lite and Kiwix, who will install the data?

 

I think deciding on scenarios, will help us to decide what options are required, and which ones we can do without.

 

Bernd

**Comment by hackersforcharity** [comment]
The USB install currently only installs a fresh firmware image. This image
(currently on Google Drive) is great to provide with each CAP as a recovery
USB in case it "crashes."

I will work to incorporate a build that includes content as well. I think
that would be very useful as a full installer and not to complicated to
build out. The only recommendation is to use a USB3 drive or the "full"
install may take a long while.

When I do the full install, would a full English build (what's currently
avail on dev.worldpossible.ord/mods) be acceptable to start with?

Sam

On Jul 30, 2015, at 19:52, bnordha <notifications@github.com> wrote:

Jeremy



You raise a good point, but I think it brings up a fundamental question.
How do you see the install script being used? Is it is just for internal
purposes, and the main install is done through the USB recovery method?


Then second, for things like Ka-lite and Kiwix, who will install the data?



I think deciding on scenarios, will help us to decide what options are
required, and which ones we can do without.



Bernd

**Comment by j-schwartz** [comment]
Hey Guys,

I think my original point here got a little sidetracked.  I'm just saying
during the install script, it'd be nice to have the option to go back to a
prior question or abort the script.  I'm not talking about anything to do
with recovery drives or anything like that.

Sorry for the confusion.

Best,
Jeremy

**Comment by spatiald** [comment]
Ha! No worries Jeremy. I have a fix that should meet your needs. Working on
it.  A dev version is in testing folder on Github. Not fully ready yet.

On Aug 6, 2015, at 12:38, Jeremy Schwartz <notifications@github.com> wrote:

Hey Guys,

I think my original point here got a little sidetracked. I'm just saying
during the install script, it'd be nice to have the option to go back to a
prior question or abort the script. I'm not talking about anything to do
with recovery drives or anything like that.

Sorry for the confusion.

Best,
Jeremy

On Mon, Aug 3, 2015 at 9:52 AM Hackers for Charity <notifications@github.com
>
wrote:

> The USB install currently only installs a fresh firmware image. This image
> (currently on Google Drive) is great to provide with each CAP as a
recovery
> USB in case it "crashes."
>
> I will work to incorporate a build that includes content as well. I think
> that would be very useful as a full installer and not to complicated to
> build out. The only recommendation is to use a USB3 drive or the "full"
> install may take a long while.
>
> When I do the full install, would a full English build (what's currently
> avail on dev.worldpossible.ord/mods) be acceptable to start with?
>
> Sam
>
> On Jul 30, 2015, at 19:52, bnordha <notifications@github.com> wrote:
>
> Jeremy
>
>
>
> You raise a good point, but I think it brings up a fundamental question.
> How do you see the install script being used? Is it is just for internal
> purposes, and the main install is done through the USB recovery method?
>
>
> Then second, for things like Ka-lite and Kiwix, who will install the data?
>
>
>
> I think deciding on scenarios, will help us to decide what options are
> required, and which ones we can do without.
>
>
>
> Bernd
>
>
>
> From: Jeremy Schwartz [mailto:notifications@github.com
<notifications@github.com>
> <notifications@github.com>]
> Sent: Friday, 31 July, 2015 1:26 AM
> To: rachelproject/rachelplus <rachelplus@noreply.github.com>
> Subject: [rachelplus] KA-Lite Install (#24)
>
>
>
> I think it'd be good to have some options to "go back" during some of the
> installation processee.
>
> For instance, when reinstalling KA-Lite up upgrading it, if we've already
> downloaded the assessment items package and placed it appropriately, the
> script asks for the filename. To me at least, I know the stuff is in the
> right place, and I'm not sure what filename that is. I get stuck in a
never
> ending loop.
>
> Also, in another place, if I choose not to download ka-lite_content.zip,
it
> asks if I have downloaded it elsewhere. I have, but I've also unpacked it
> elsewhere as the CAP is slow to unpack it. If I say yes at that prompt, I
> get stuck, because I don't have the zip file anywhere nor do I want to do
> the unpacking.
>
> Perhaps a "skip" or "go back" option could be enabled?
>
> —
> Reply to this email directly or view it on GitHub <
> https://github.com/rachelproject/rachelplus/issues/24> . <
>
>
https://github.com/notifications/beacon/AMmq9BBjICbBv8iqXrQwV4wRwteGWRg0ks5oilWXgaJpZM4Fi7WC.gif
> >
>
>
> —
> Reply to this email directly or view it on GitHub
> <
>
https://github.com/rachelproject/rachelplus/issues/24#issuecomment-126523448
> >
> .
>
> —
> Reply to this email directly or view it on GitHub
> <
https://github.com/rachelproject/rachelplus/issues/24#issuecomment-127329740
>
> .
>

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/24#issuecomment-128482658>
.

**Comment by spatiald** [comment]
Install script updated.  You can re-run the KA-Lite install script as many times as you wish.  It will only check to ensure it has the latest and greatest files.  It will not re-download already downloaded content/files (e.g. assessmentitems.json).  

Additionally, if you already have the content downloaded, you can just use the offline install.  It will look for the the kacontent directory to rsync or if it sees the ka-lite_content.zip, it will unzip/install.
