### ISSUE TITLE
MySQL Database

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#25]
Where should we put this so we can include it in the install process?  I just don't want to lose it.  I forgot to include it on a number of devices so far.  Any ideas?

**Comment by hackersforcharity** [comment]
Can you put it on github?  What size is it?

On Jul 30, 2015, at 18:31, Jeremy Schwartz <notifications@github.com> wrote:

Where should we put this so we can include it in the install process? I
just don't want to lose it. I forgot to include it on a number of devices
so far. Any ideas?

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/25>.

**Comment by j-schwartz** [comment]
It's 480MB, it's on rachel friends at :
http://rachelfriends.org/z-SQLdatabase/sphider_plus.sql

**Comment by spatiald** [comment]
Added to config script (Option 5).
