### ISSUE TITLE
Pre-loaded Content not being Grabbed by Intel Interface

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#26]
When adding content to the "preloaded" section via FTP, the content is not being indexed by the device.

**Comment by spatiald** [comment]
@arcangel44 @j-schwartz
This issue is related to issue #43 

From what I have tested, I tried uploading content to uploaded and preloaded with no success.  @j-schwartz  can you add this to your questions for Intel?

**Comment by spatiald** [comment]
Still looking to resolve the preloaded/uploaded partition issues.  Any content put on these partitions does not load on the Intel interface.  The content must be uploaded via the GUI for the "database" to register that it exists.

I would like a way to batch upload data to one of those partitions and for the Intel interface to recognize the new content.

**Comment by j-schwartz** [comment]
Hi Sam -

When I make copies of drives, I have content installed in the 'preloaded'
partition (teacher's editions of CK12 textbooks) and I have no issues when
I swap those drives into units.

The batch upload also worked for me, as long as there is no folder
hierarchy.  The documents all had to be in a single folder as individual
files.

Are you experiencing something different?

**Comment by spatiald** [comment]
Yes - not with uploading content via Intel interface. However, if I
manually upload content to the partition, it isn't recognized by the
Intel interface.

For instance, if I rsync a bunch of content to the partition.

**Comment by j-schwartz** [comment]
Got it, so after the device is up and running, if you rsync a bunch of
individual PDFs (not in folders) to "preloaded" - they aren't recognized by
the Intel software, even after a reboot?

**Comment by spatiald** [comment]
Yes, that has been my experience.

**Comment by spatiald** [comment]
Okay, think I partially figured out intent for preloaded/uploaded. 

Preloaded:
- admins add this content in the form of a zip file of content
- upload screen is when logged into "admin mode" (versus "teacher mode")

Uploaded:
- teachers upload content as individual items
- upload screen is when logged in as teacher *or* in "teacher mode" when logged in as admin

Adding content to either the preloaded or the uploaded partitions will not add it to the CAP so it's accessible to users. You have to add it through web interface.
