### ISSUE TITLE
Steps pre-shipping after dual imaging

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#27]
As much a reminder for myself as anything, these are the things that need to get done right now after using Sam's recovery image and an image of the 500GB HDD I am cloning:

0) run install script 

```
su
12l3kj
bash /media/RACHEL/cap-rachel-configure.sh
1
```

1) install mysql database
```
sudo sed -i '52,58d' /media/RACHEL/rachel/index.php
```

1b) Fix KA-lite
```
sudo /media/RACHEL/ka-lite/bin/kalite manage setup
```
no, yes, yes

2) configure settings MPT tool
SSID: RACHEL_Plus_##
Wireless Settings: Anti-Interference Mode: On
Security Mode: WPA
Add Password: worldpossible

3)
```
sudo cp /media/RACHEL/rc.local /etc/rc.local

sudo /media/RACHEL/kiwix/bin/kiwix-manage /media/RACHEL/kiwix/data/library/library.xml add /media/RACHEL/kiwix/data/content/wikipedia_en_all_2015-05.zim --indexPath=/media/RACHEL/kiwix/data/index/wikipedia_en_all_2015-05.zim.idx

```

**Comment by j-schwartz** [comment]
Moving KA-Lite and Kiwix to 2.5" drive to avoid redoing these steps.

**Comment by spatiald** [comment]
##### Want needs to be mod'd in the config script for your steps?
- the script will install mysql (during Option 1) and the sphider database now (Option 5)

##### What does the following line do for you?
```
sudo cp /media/RACHEL/rc.local /etc/rc.local
```
I modify the /etc/rc.local file already and you might be stepping on my additions...maybe?  Here are the relevant lines from my /etc/rc.local that are added during various config script steps:
```
# Start ka-lite at boot time
sleep 20
/var/ka-lite/bin/kalite start
# Start kiwix on boot
bash /var/kiwix/bin/kiwix-serve --daemon --port=81 --library /media/RACHEL/kiwix/data/library/library.xml
# RACHEL iptables - Redirect from 10.10.10.10 to 192.168.88.1
bash /root/iptables-rachel.sh&
exit 0
```
##### What do you mean by "Moving KA-Lite and Kiwix to 2.5" drive"?
There is an option to download RACHEL content for OFFLINE install (Option 6 then Option 1).  It will download/refresh the following files to a location of your choice:
  - contentshell (GitHub Repo)
  - ka-lite (GitHub Repo)
  - rachelmods (module directories from dev.worldpossible.org)
  - rachelplus (GitHub Repo)
  - ka-lite_content.zip (rachelfriends.org)
  - kiwix-0.9-linux-i686.tar.bz2 (rachelfriends.org)
  - sphider_plus.sql (rachelfriends.org)

The OFFLINE install is not wholly offline (apt-get and mysql still need internet) but the whole install is EXTREMELY low on internet bandwidth usage.

For a successful OFFLINE install, you need to have the above folders/files in your OFFLINE content storage.
##### MPT / Web interface settings
Unfortunately, I don't have an effective way to modify these settings during install.  Using the MPT or web interface are your best options.  If Gemtek provides that information (Bernd is working on it), then maybe we can do this with initial install.

On your wifi settings, you mention "RACHEL_Plus_##"...what do the last two digits ## signify?

Are you encrypting your wifi now with WPA?

**Comment by j-schwartz** [comment]
This is great.  Most of my post is slightly tailored to the distributions we're sending the correctional facilities, but I'll try to tick through comments:

I was starting with the 1.2.13_rooted image you created.  That image didn't have kiwix installed by default or KA-Lite (I believe).  Just meant that for each device (50) I had to install them on the eMMC.  Instead of doing that, I installed them once on the "media" 2.5" HDD and cloned that device as well. 

I also created an etc/rc.local file that included kiwix booting up, which the 1.2.13_rooted image didn't do for me.  I placed it on the /media drive and just copy it over, as that is easier than editing the file for each device.

The MySQL database also wasn't pre-installed on the eMMC drive.  So I put in on the 2.5" drive and just copy it into place.

That's pretty much everything.  I'm going to see what the new USB recovery image creates now.  I'm adding the last two digits of the WFM ID to the end of the RACHEL_Plus_##.  That way in facilities with more than one device they can physically identify them easily.  Also avoids people having accounts on one and not the other and not knowing which to connect to.

I do add WPA security, but just for the prison deployment.

**Comment by j-schwartz** [comment]
my /etc/rc.local

```


# RACHEL iptables - Redirect from 10.10.10.10 to 192.168.88.1
bash /root/iptables-rachel.sh&

# KA-Lite
sleep 10;
/media/RACHEL/ka-lite/bin/kalite start

#Kiwix and Wikipedia
/media/RACHEL/kiwix/bin/kiwix-serve --daemon --port=81 --library /media/RACHEL/kiwix/data/library/library.xml

exit 0


```

**Comment by spatiald** [comment]
@j-schwartz So would it be helpful for you if I built in different content scenarios into the configure script. So, to start from scratch, you would only have to run install and then content for a given scenario (ie prison)?

When starting from a scratch CAP, you have to go through the imaging process on the RACHEL partition.  That causes an issue with installing content during the install process as you have to reboot twice. 

What do you foresee as the default English build?
- KA Lite
- GCF
- Kiwix with full Wikipedia 
- All other non-KA/wiki content

Sam

**Comment by j-schwartz** [comment]
As far as I can tell, with the new USB, there is nothing that really needs to be done pre-shipping except customize content.  I'm also removing the search bar for now, but @needlestack is working on a modular search build.
