### ISSUE TITLE
Kiwix fails to start on boot

### ISSUE THREAD

**Issue by spatiald** [rachelproject/rachelplus#29]
Installed kiwix with config script.  Kiwix is set to start on boot with the following command:
```bash
bash /var/kiwix/bin/kiwix-serve --daemon --port=81 --library /media/RACHEL/kiwix/data/library/library.xml
```
Error on boot:
```
/var/kiwix/bin/kiwix-serve: /var/kiwix/bin/kiwix-serve: cannot execute binary file
```

**Comment by j-schwartz** [comment]
What kiwix content file do you have included in there?  I thought I had all of wikipedia included on my drive, and one of the .zim parts was not fully completed.  Withing /media/RACHEL/kiwix/data/content you can just confirm that all parts (except the last one) are the same size.

Obviously, if kiwix boots after start-up, this isn't the issue.

I also don't include the "bash" pre-fix.

**Comment by spatiald** [comment]
Bash pre-fix was a test.

Is the data required prior to start Kiwix?  I didn't download any data;
just installed the program. The config script installer doesn't do content
install. I can add a small one if needed.



On Aug 17, 2015, at 11:37, Jeremy Schwartz <notifications@github.com> wrote:

What kiwix content file do you have included in there? I thought I had all
of wikipedia included on my drive, and one of the .zim parts was not fully
completed. Withing /media/RACHEL/kiwix/data/content you can just confirm
that all parts (except the last one) are the same size.

Obviously, if kiwix boots after start-up, this isn't the issue.

I also don't include the "bash" pre-fix.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/29#issuecomment-131865921>
.

**Comment by bnordha** [comment]
Does Kiwix start when you execute that line on the command line?

**Comment by bnordha** [comment]
Yes, it requires data. I have included the small Ray Charles Wikipedia as a test file.

**Comment by spatiald** [comment]
Nope :)  Unfortunately not.  I was hoping I was missing something.  Do I need to have a default module installed?  Am I missing how Kiwix is incorporated into the menu?

**Comment by bnordha** [comment]
Do you get any error message when you execute

sudo /var/kiwix/bin/kiwix-serve --daemon --port=81 --library /media/RACHEL/kiwix/data/library/library.xml

                                   

Did you download the Ray Charles testfile?

 


# Download a test file  

	
  cd /media/RACHEL/kiwix

	
  wget http://rachelfriends.org/z-holding/Ray_Charles.tar.bz

	
  tar xjvf Ray_Charles.tar.bz

	
  

	
   cp /media/RACHEL/kiwix/data/library/wikipedia_en_ray_charles_2015-06.zim.xml  /media/RACHEL/kiwix/data/library/library.xml

**Comment by bnordha** [comment]
I tested the install and observed two issues:

 

1)      The files under /var/bin are not executable.

2)      When the data files are missing, the process  sudo /var/kiwix/bin/kiwix-serve --daemon --port=81 --library /media/RACHEL/kiwix/data/library/library.xml will not start.

After I made the /var/bin/ files executable and installed the test files, things are working fine.

**Comment by spatiald** [comment]
Thanks - I tested the same last night. I made mods to the configure script
and will post today. Working one more bug out first.

Thanks for testing!

On Aug 18, 2015, at 04:20, bnordha <notifications@github.com> wrote:

I tested the install and observed two issues:



1) The files under /var/bin are not executable.

2) When the data files are missing, the process sudo
/var/kiwix/bin/kiwix-serve --daemon --port=81 --library
/media/RACHEL/kiwix/data/library/library.xml will not start.

After I made the /var/bin/ files executable and installed the test files,
things are working fine.



—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/29#issuecomment-132117985>
.

**Comment by spatiald** [comment]
Okay...looks like it was a the two issues that @bnordha mentioned.  Fixed in the configure script.
