### ISSUE TITLE
KA Lite doesn't start up after "unclean shutdown"

### ISSUE THREAD

**Issue by spatiald** [rachelproject/rachelplus#30]
KA Lite starts normally if running on shutdown/reboot.

KA Lite doesn't start if not running due to "stop" or "unclean shutdown".

Tried various bash scripting and settings with /etc/rc.local.

Anyone else seen this issue?

**Comment by j-schwartz** [comment]
How can I replicate a "stop" or "unclean shutdown"?

**Comment by bnordha** [comment]
Yes, I have. I wasn’t able to replicate the issue though.

**Comment by spatiald** [comment]
An unclean shutdown is replicated by typing “reboot” from the command line of the CAP.  This doesn’t allow KA Lite to properly shutdown.

**Comment by j-schwartz** [comment]
I've done that multiple times and have never noticed KA-lite not starting
on the reboot.  Perhaps I need to double check, but I really haven't
noticed this issue.

I have definitely gone to check and like the Pi's, KA-lite hasn't booted up
yet though the web server is running.  Within 30 seconds, and sometimes
after clearing my web cache (frequently), I've never not gotten KA-lite.

**Comment by hackersforcharity** [comment]
Hmmm…maybe it’s my install; I’ll test on a different one and see if it’s just me…probably me :)

**Comment by bnordha** [comment]
I tested different scenarios including

*         Shutdown now

*         Hard reboot

 

I was not able to replicate the issue. Ka-lite started every time.

**Comment by hackersforcharity** [comment]
Sweet, thx for testing. My Dev environment must be out of whack. Rebuilding
:)



On Aug 18, 2015, at 04:17, bnordha <notifications@github.com> wrote:

I tested different scenarios including

* Shutdown now

* Hard reboot



I was not able to replicate the issue. Ka-lite started every time.



—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/30#issuecomment-132116425>
.

**Comment by spatiald** [comment]
Believed to be non-issue, closing.
