### ISSUE TITLE
Script creating directory on not yet existent RACHEL partition

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#31]
I may have just had a bad batch of harddrive clones, but I'm getting this new message:

```
2015-08-25 01:48:50 (2.80 MB/s) - `/root/cap-rachel-configure.sh' saved [54166/54166]

mkdir: cannot create directory `/media/RACHEL/cap-rachel-install.tmp': Permission denied
/root/cap-rachel-configure.sh: line 35: print_error: command not found
```

**Comment by spatiald** [comment]
Weird…are you running the script as root?  If so, check ‘df -h’ as I don’t think the /media/RACHEL partition exists are was imaged correctly.

**Comment by j-schwartz** [comment]
Correct, the RACHEL partition doesn't exist.  Pretty strange.  Using a cloning box for it that I bought just to clone hard drives.  I wonder if some CAPs have smaller actual internal storage for their 2.5" HDD.  

I'm going to use the new image recovery USB and script sets starting today.  Have just been a little swamped getting devices out and didn't want to change up my process yet.

**Comment by spatiald** [comment]
The recovery usb is designed for recovering and will not image the /dev/sd3 partition of the CAP.  I was thinking about making a new USB imager that would setup the RACHEL in a basic form, ready for content.  Would that be helpful?

sam

**Comment by j-schwartz** [comment]
In an ideal world, I'd love to be able to prepare a CAP without having to individually log into it.  It'd be like a three step process:

1) Plug in USB recovery (which I'll make dozens of)
2) Plug in cloned harddrive from clone box (which I'll make dozens of)
3) Use MPT tool to configure basic network settings

Then ship.  

Right now I'm trying to minimize the time it takes to create one for shipping.  I'm well behind in shipping out devices.

**Comment by j-schwartz** [comment]
Thought about another way, the recovery USB would enable someone with no technical expertise to recover their CAP if something happen to it. 

Plug the recovery USB in, let it do it's thing to recover the CAP to a bootable and workable state, but the 2.5" harddrive would not be affected.

**Comment by j-schwartz** [comment]
Sorry, I'm catching up slowly.  I get what you're saying now.  

Yes, it'd be awesome to get a second 'USB recovery' aka 'USB setup'.  The recovery drive basically can be shipped with the CAPs to do what I want it to, right? 

The 'USB setup' would be amazingly helpful also, just for internally.  With the last USB recovery drive, I was able to quickly run the setup scripts as my first step.  I think I can do that with the new USB recovery drive also, if I had a good clone of the 2.5" drive.

Sorry, just catching up to you slowly here.

**Comment by spatiald** [comment]
Yes - that's the premise behind two USB methods. I started creating the
files on rachelplus Git. One is a USB recovery for clients and another is a
USB imager for installers.  I do believe it might be possible to build an
imager that also images the hard drive but that's not tested yet.



On Aug 24, 2015, at 13:14, Jeremy Schwartz <notifications@github.com> wrote:

Thought about another way, the recovery USB would enable someone with no
technical expertise to recover their CAP if something happen to it.

Plug the recovery USB in, let it do it's thing to recover the CAP to a
bootable and workable state, but the 2.5" harddrive would not be affected.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/31#issuecomment-134305033>
.

**Comment by hackersforcharity** [comment]
No worries ... Lots of activity over the last week. You need to check out
the new build if the recovery script. My current idea is to create a USB
imager that will prep to the point of adding content. Then use the
configure script to add the content of your choice for the client that
requested it. I already have the start of customizable content on the
configure script.

On Aug 24, 2015, at 13:23, Jeremy Schwartz <notifications@github.com> wrote:

Sorry, I'm catching up slowly. I get what you're saying now.

Yes, it'd be awesome to get a second 'USB recovery' aka 'USB setup'. The
recovery drive basically can be shipped with the CAPs to do what I want it
to, right?

The 'USB setup' would be amazingly helpful also, just for internally. With
the last USB recovery drive, I was able to quickly run the setup scripts as
my first step. I think I can do that with the new USB recovery drive also,
if I had a good clone of the 2.5" drive.

Sorry, just catching up to you slowly here.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/31#issuecomment-134307292>
.

**Comment by spatiald** [comment]
This is what I am going to test:

1. USB drive for imaging that will upgrade the firmware and image the core
OS with a default shell install (no content) of RACHEL, Kiwix, KA Lite,
Sphider.

2. Drop in your cloned drive (that was sanitized via script, then cloned).

3. MPT tool for network settings (like you said)


Are you planning on including a USB recovery drive (non-destructive to the
hard drive) with the CAP or just online for folks to download?

**Comment by j-schwartz** [comment]
That sounds amazing.  I will plan on shipping the drive to anyone who is
taking it overseas.  I probably won't include for deployments in the U.S.
(prison systems).

I'm going to treck back through some of the stuff I know I've missed.  I
have a question about registering KA-lite but want to find the right issue
for it.

**Comment by spatiald** [comment]
@j-schwartz Check out the new USB RACHEL Multitool post in Issue #18.  I think it will solve these issue that you are having and make your mass image/cloning much easier.  Re-open this issue if you think we need to.
