### ISSUE TITLE
RACHEL search function

### ISSUE THREAD

**Issue by spatiald** [rachelproject/rachelplus#32]
This was noted before but I think we need to identify a new way to do searching within RACHEL.  Jeremy and I spoke of an issue that the justice folks relayed...they would search and then the results would populate but link to a 404.  I looked into it tonight and the problem lies in the fact that the sphider database we use is linked to content that was on the device when the database was initially populated.  

For instance, these links no longer work because we are now using the full Wikipedia and KA Lite as the primary modules (at least for CAP):

[http://192.168.88.1/modules/khan_academy/science/physics/work-and-energy/hookes-law/spring-potential-energy-example--mistake-in-math.html](http://192.168.88.1/modules/khan_academy/science/physics/work-and-energy/hookes-law/spring-potential-energy-example--mistake-in-math.html)

[http://192.168.88.1/modules/wikipedia_for_schools/wp/e/Education_in_the_United_States.htm](http://192.168.88.1/modules/wikipedia_for_schools/wp/e/Education_in_the_United_States.htm)

**Comment by j-schwartz** [comment]
I've talked at length about this with some users and I think we all agree
it may be best to remove global search from the CAP, which uses KA-Lite and
full Kiwix Wikipedia.

Thoughts?

**Comment by spatiald** [comment]
I think that makes sense for now.

I have experimented with yacy (another search engine) but even though the
interface is great and it can be customized for us, it's database can't
easily be controlled and grows and grows and grows. I'll put up a link to
my yacy portal running on a demo cap.


On Sep 15, 2015, at 13:13, Jeremy Schwartz <notifications@github.com> wrote:

I've talked at length about this with some users and I think we all agree
it may be best to remove global search from the CAP, which uses KA-Lite and
full Kiwix Wikipedia.

Thoughts?

On Wed, Sep 9, 2015 at 6:00 PM Sam Kinch <notifications@github.com> wrote:

> This was noted before but I think we need to identify a new way to do
> searching within RACHEL. Jeremy and I spoke of an issue that the justice
> folks relayed...they would search and then the results would populate but
> link to a 404. I looked into it tonight and the problem lies in the fact
> that the sphider database we use is linked to content that was on the
> device when the database was initially populated.
>
> For instance, these links no longer work because we are now using the full
> Wikipedia and KA Lite as the primary modules (at least for CAP):
>
>
http://192.168.88.1/modules/khan_academy/science/physics/work-and-energy/hookes-law/spring-potential-energy-example--mistake-in-math.html
>
>
>
http://192.168.88.1/modules/wikipedia_for_schools/wp/e/Education_in_the_United_States.htm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rachelproject/rachelplus/issues/32>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/32#issuecomment-140468202>
.

**Comment by bnordha** [comment]
I fully agree. I also spend some time looking at Sphider and had an email exchange with Jonathan who I build the current index database. 

 

In my humble opinion Sphider is not ready for prime time, and not well suited for Rachel. For example, Sphider does not support relative URL’s. That means, after indexing, you need to change the URL’s manually in the database from absolute to relative URL’s so that it works across different deployments.

 

I had a cursory look at Sphinx (http://sphinxsearch.com/) It might be worth looking deeper into it to see whether it can be adapted for Rachel.

**Comment by spatiald** [comment]
I think this issue was resolved by @needlestack 

Reopen, if needed.
