### ISSUE TITLE
Helping a N00b with CAP Ubuntu :) I will send chip chocolate cookies 

### ISSUE THREAD

**Issue by arcangel44** [rachelproject/rachelplus#43]
Hi! I need to upload some content (pdf and stuff) to CAP using SSH. I found the media folder and add some documents there, but when i'm in Chrome, using the CAP interface in the lesson planner I can't found them. I only tried uploading without compressing and adding them to a existing folder. Can anyone help me to figure out how i can visualize them in CAP web interface?  What i'm doing wrong? Thanks!

**Comment by j-schwartz** [comment]
I'm not an expert on this, but I think you need to upload them as single files (not within a folder) directly to the uploaded section.  are you adding documents directly into /media/uploaded/ ? 

Also try rebooting after, just for kicks.

**Comment by j-schwartz** [comment]
also, when you've ssh'd in your new files, please check your permissions settings on them.  I don't know what they're supposed to be, but you can try making them very open 

```
chmod -R 0755 /media/uploaded/
```

**Comment by spatiald** [comment]
Question for you…are you using a RACHEL CAP or plain Intel CAP?

If you using a RACHEL CAP, the easiest way to upload your files is via the web interface at:
http://192.168.88.1:8090 <http://192.168.88.1:8090/>

Login with:
User:  teacher
Password:  teacher

Go to the “Library” tab and click the “Upload Content” button


sam@hackersforcharity.org
302.482.4586

**Comment by arcangel44** [comment]
Yes, i can upload content using the web interface but that's exactly what i don't want. I want to be able to upload content using only SSH and be able to see it in the web interface. On the other hand, I will try to do that, open the documents, because i only uploaded them to /media/uploaded/FolderX and no in /media/uploaded/

**Comment by j-schwartz** [comment]
Any word on this @arcangel44

**Comment by spatiald** [comment]
@arcangel44 @j-schwartz
This issue is related to issue #26 

Closing this issue and consolidating comments there.
