### ISSUE TITLE
CAP does not safely shut down

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#44]
At one point I found a script used to measure voltage and initiate a shutdown at for our "Rugged Pi" through the forums on that UPS here: http://www.forum.pimodules.com/viewforum.php?f=12&sid=b3179bf33e88f9f3ba91fc1b3f8fe5e1

I know the script required some amount of battery reading.  Intel has provided the following information:

For battery level, read:

/tmp/batteryLastChargeLevel

To disable the factory reset button:

Kill the process “reset_button”

**Comment by spatiald** [comment]
I added a battery monitor feature...
1. ./cap-rachel-configure.sh -u (use the download script if you don't the self-update feature)
2. ./cap-rachel-configure.sh -i, option 8, option 1

Fixed; reopen, if necessary.
