### ISSUE TITLE
Custom Linux installable image for Intel CAP

### ISSUE THREAD

**Issue by jjmuriel** [rachelproject/rachelplus#46]
Hi,
Although I have experience in Linux and its administration, I am new to customize images to install in embedded devices like the Intel CAP.  I found the work of this organization very interesting and it has served as an inspiration for me,  for wanting to create and customize a image for the Intel CAP that suits the needs of the schools in my country, Colombia. Thanks for sharing this valuable project to the world. Could you please tell me where to start building a custom image that I can install Linux on Intel CAP and how I can deploy it in this device (a link to a tutorial and how  can I create an installable image for the Intel CAP)?. In advance thank you very much for your help.

**Comment by j-schwartz** [comment]
Hi @jjmuriel - you can install all of RACHEL by following the readme at the main page of this github.  Our content and scripts are free to use.  

If you want  to add Columbian specific websites and content, we can help you package those if you have the content available.

Best,
Jeremy

**Comment by jjmuriel** [comment]
Thank you very much for your answer. More than content, I mean to make modifications to the operating system to add features such as the possibility of installing a VPN server or put to work the 2.4 GHz  and 5 GHz bands simultaneously.  As the projects OpenWRT or DD-WRT do.

**Comment by jjmuriel** [comment]
Maybe these photos can be used to adapt other operating systems or the same Ubuntu:
![20160208_202752](https://cloud.githubusercontent.com/assets/17131600/13258421/1131812c-da21-11e5-8a33-3b4558850e98.jpg)
![20160208_203054](https://cloud.githubusercontent.com/assets/17131600/13258469/3be50bc8-da21-11e5-9c32-51b090de2349.jpg)
![20160208_203324](https://cloud.githubusercontent.com/assets/17131600/13258506/68cc2edc-da21-11e5-8c0b-9146431e9fff.jpg)
![20160208_214430](https://cloud.githubusercontent.com/assets/17131600/13258569/a891a434-da21-11e5-96e6-10d915212ed8.jpg)
![20160208_213227](https://cloud.githubusercontent.com/assets/17131600/13258605/cd6353fc-da21-11e5-9fb5-2e36e3785494.jpg)
![20160208_213839](https://cloud.githubusercontent.com/assets/17131600/13258629/ec23bc96-da21-11e5-835d-b74cca9a825b.jpg)

**Comment by spatiald** [comment]
A lot of development work was discussed [here](http://rachel.golearn.us/wiki).  You might be interested in the serial write-up located on this site as it will allow to troubleshoot the CAP during the actual boot process.

Generic images of the CAP firmware can be found [here](ftp://ContentAccessPoint:FWRelease@ftp.gemteks.com).

Good luck with your customized version!

**Comment by jjmuriel** [comment]
Thank you very much for your answer. I'll visit the Wiki.

**Comment by Achemi1** [comment]
Thanks for The message.

-----Original Message-----
