### ISSUE TITLE
Bricked CAP

### ISSUE THREAD

**Issue by arcangel44** [rachelproject/rachelplus#47]
Hi! I have a bricked CAP and I need to fix it. I tried via USB Recovery but I failed several times because CAP does not simply recognize the USB and "starts normally" (Breathing led). I tried to access to HDD but i failed because there's only Uploaded and Preloaded content, am I wrong? Do you know any solution to this? Thanks! :D

**Comment by arcangel44** [comment]
Forget it, this is how i solve it: 
1. Remove the HDD 
2. Wait for some error indicator 
3. Turn off and do the USB recovery
:D

**Comment by j-schwartz** [comment]
Amazing.  Did you remove the HDD while the device was on?  How did you
identify an error indicator?

**Comment by arcangel44** [comment]
No, i remove the HDD when the device was off and then I turned it on, Wi-Fi indicator turn on orange. Turned off again and i started the USB recovery normally.

**Comment by j-schwartz** [comment]
Fantastic.  Good to know, thanks for the update.
