### ISSUE TITLE
Intel / Gemtek Original images

### ISSUE THREAD

**Issue by jjmuriel** [rachelproject/rachelplus#52]
Since it took me almost four days to downloading the original images of the Intel CAP (ftp://ContentAccessPoint:FWRelease@ftp.gemteks.com/), because the server speed is very low ( ~ 50KB/S), I bring you this images here, available to the users of this repository, into the Google Drive Servers. I expect you find it useful:

https://drive.google.com/open?id=0B9LI1yW71wEyNWdzcUIzaWFnVjg

**Comment by spatiald** [comment]
Thanks!
