### ISSUE TITLE
LAN Connections to Rachelplus

### ISSUE THREAD

**Issue by click2tman** [rachelproject/rachelplus#53]
I am having problem connecting a LAN to the server. This is my use case;

I want to connect 10 Ubuntu desktops already on a LAN and 20 plus wireless devices to the Rachelplus. I noticed that the Ethernet port on the Rachelplus is not a LAN port. How will I be able to do this?
Here is my situation;
I have 10 Ubuntu desktops on a LAN. A switch connects all 10 machines. I have a TPLink Wireless Router. I use the TPLink wireless router as DHCP server to issue IP addresses to the Ubuntu desktops. I have a small ubunter server running offline websites. This server is also connected to the TPLink. This way, users on the LAN and WLAN can both see the content on the server. My Server have IP address 192.168.1.5, TPLink have IP Address 192.168.1.1 and all Ubuntu desktops have IP addresses ranging from 192.168.1.10 to 192.168.1.20. The default gateway is 192.168.1.1 and the DNS is 192.168.1.1 on the server and desktops. This setup works fine as desires. I want to remove the server and tplink if possible and use the rachelplus. I changed the ip addresses of my desktops to match the rachelplus WLAN network and connected an Ethernet cable from the WAN port of the Rachel plus to my switch. But this is not working on the desktops.

**Comment by spatiald** [comment]
The RACHEL-Plus ethernet port is not setup to provide DHCP.  DHCP is only
provided to Wifi users.  The ethernet port is setup as a WAN port and
should be plugged into your switch which, in turn, is plugged into your TP
Link for internet.

Internet --- TP Link --- Switch----Clients (10 machines + RACHEL-Plus)

If you want to configure a static IP, I recommend that you assign it a DHCP
Static Mapping on your TP Link.  However, you can also set it on the
RACHEL-Plus here --> http://192.168.88.1:8080/wan_settings.html (when
connect via wifi).

**Comment by spatiald** [comment]
"LAN Mode" requested as an enhancement request in [issue #16](https://github.com/rachelproject/rachelplus/issues)
