### ISSUE TITLE
KA-Lite 0.16.5 - perhaps critical errors in 16.1

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#56]
Hi Guys - 

trying to find a place to track changes, but so far as I can tell, 0.16.1 has quite a few bugs (including not moving on exercises automatically and trapping users in never ending loops of exercises).

They're up to version 0.16.5 on the official release site, I think we need to consider getting there as well

**Comment by j-schwartz** [comment]
This appears to have to do with my setup, I'll need to recreate, but the same behavior exists in 0.16.5

First after finishing a video:

![image](https://cloud.githubusercontent.com/assets/9270388/15517991/8165a04c-21af-11e6-94ea-ad39a5d3c67d.png)

Second, exercises go in an infinite loop

**Comment by hackersforcharity** [comment]
That is an easy change and update. I'll push a USB recovery and configure
script tonight. Thanks for the info.

On May 24, 2016, at 13:51, Jeremy Schwartz <notifications@github.com> wrote:

Hi Guys -

trying to find a place to track changes, but so far as I can tell, 0.16.1
has quite a few bugs (including not moving on exercises automatically and
trapping users in never ending loops of exercises).

They're up to version 0.16.5 on the official release site, I think we need
to consider getting there as well

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/56>

**Comment by j-schwartz** [comment]
So I spent a bit of time on github for KA-Lite, and I'm venturing to say they are close to not really supporting it much at all...

My vote may be for us to find a good last working version and sit on it for a while, unless you guys aren't having any trouble.

My major issues are after videos, an error appears 

Sorry, this request could not be processed. Please try again later.

And for exercises, even logged in as a learner, I can go on forever taking exercises.

**Comment by j-schwartz** [comment]
I just found this on the google group:

Hi all,

Despite our intention, we've missed our initial goal of releasing KA Lite 0.16.0 in mid-February. There are a few reasons for this, including:

* We discovered some bugs and rough edges that we wanted to get rid of before release.
* We want to test on many different platforms (various versions of Windows, OSX, Ubuntu, and Raspbian), which is time consuming.
* Our development resources are still badly split between Kolibri and KA Lite.

Nonetheless, a 0.16 beta version of the ka-lite package are now available on PyPI!

Our plan moving forward is to release KA Lite 0.16.0 by 3/18. We feel we're much closer to this goal, as we've been steadily closing existing issues and testing has turned up only a handful more.

In the meantime, Kolibri development has been somewhat impeded. Since we have identified splitting our attention between Kolibri and KA Lite as a major cause of slowdown on both projects, we're aiming to finally release 0.16.0 and then focus entirely on Kolibri.

We have several near-term goals of refining the existing kolibri.auth and kolibri.core apps:
* Re-writing the permissions system (PR here, including link to documentation)
* Integrating Django REST Framework into kolibri.content
* Completing a manifest of common UI components and implementing them in Backbone (manifest, and visual design folder)

Starting on 3/23, we'll begin focusing on developing several plugins for Kolibri. The development team has met briefly a couple times to flesh out the plugin system, and we feel it would be best driven by developing several small, relatively self-contained plugins. We've compiled a list of ideas and we're going to devote two days to hacking on them:
* A "nav" app defining an API for adding navigation items to menus, including different menu types
* A set of base templates utilizing the nav app, so that plugin authors can focus on content instead of repeating common elements.
* Content viewing plugins for viewing & interacting with different content MIME types
* A user management app for creating/editing user accounts and permissions

We invite you to contact us if you'd like to join these hack sessions remotely!

Best,
Mike

**Comment by j-schwartz** [comment]
Further confirmation: 

We’ve been ramping up development of our newest project, Kolibri, which will do everything that KA Lite does, and much more! As a result, KA Lite 0.16 will be our last major release. We’ll continue to have minor releases for bugfixes and updates of Khan Academy content, but our team will mostly be focused on making Kolibri a reality.  Want to contribute to its development? Join our development community!

**Comment by j-schwartz** [comment]
Exercises can go on forever in a loop:

![image](https://cloud.githubusercontent.com/assets/9270388/15523542/0eaba94a-21d0-11e6-8f35-46fe0940453a.png)

There's an annoying feedback box, which can't be submitted, and is always present:

![image](https://cloud.githubusercontent.com/assets/9270388/15523548/2328365e-21d0-11e6-932e-cf7ccab22331.png)

**Comment by richsegal** [comment]
I have run into another serious issue as well.   The newly revamped closed captioning code in KA-Lite 0.16.x does not work in Epiphany.  As a result, there is no way to view captions on a Raspberry Pi. We have reverted to 0.15.x for our most recent powering potential RACHEL releases.

**Comment by rtibbles** [comment]
The feedback box does not need to be submitted. You just rate it, and the rating is saved.
(Please see the User Manual for more information on Content Rating: http://ka-lite.readthedocs.io/en/latest/usermanual/userman_learner.html#content-rating )

We are currently triaging issues for a 0.16.6 release, as we try to track down some issues in our pipeline of drawing translated content down from Khan Academy (the data we seem to be getting from their public APIs seems to be a subset of what is actually translated there), as we are keen to provide our non-English speaking users with as good an experience as our English speaking ones, this has been our priority at the moment.

Happy to review PRs that help with the issues that are concerning you, re: the exercise interaction, and please do send us some more information about the videos if that is happening for student accounts.

**Comment by jamalex** [comment]
> I'm venturing to say they are close to not really supporting it much at all...

Just to clarify on this point, we definitely still plan to continue supporting KA Lite, until it is fully subsumed by Kolibri (with a Khan Academy channel) and we have a clear migration path for users/data (which is probably about a year out). What we aren't doing at this point (because our resources are dedicated to meeting deadlines for Kolibri development) is developing new features for KA Lite. The goal is to stabilize the 0.16.x release line with bugfix patch releases so that it will be reliable and robust for users while Kolibri development is in progress.

> As a result, there is no way to view captions on a Raspberry Pi. We have reverted to 0.15.x for our most recent powering potential RACHEL releases.

There are very significant performance improvements (and other fixes) in 0.16, so it would be good to get things patched up so you're able to use it. Has a ka-lite issue been opened regarding subtitles for Epiphany?

**Comment by spatiald** [comment]
Latest v8 RACHEL Recovery USB updates KA Lite to 0.16.6post1 

The [latest configure script](https://github.com/rachelproject/rachelplus/blob/master/cap-rachel-configure.sh) is updated as well to install 0.16.6post1

This resolved many of the issues previously mentioned. The only outstanding issue is session tracking and login count as noted [here](https://github.com/learningequality/ka-lite/issues/5157)

According to Learning Equality folks, "Issue [5180](https://github.com/learningequality/ka-lite/pull/5180) has already been merged, so you can check out the repo directly, try the 0.16.7 debian pre-release on PPA, or the latest Win build in Dungeon"

Closing this issue as the original issue point was resolved. I'll test .7 but upgrading to .6 should solve the majority of issues.
