### ISSUE TITLE
Is this an issue?  Script to install Kiwix

### ISSUE THREAD

**Issue by j-schwartz** [rachelproject/rachelplus#63]
Hi Guys -

I was going through the build process using cap-rachel-configure.sh

I accidently chose option 3, install Kiwix, instead of option 4, for installing weaved.  I'm wondering, does choosing option 3 screw up our most recent library.xml build, which seems to build automatically?

![image](https://cloud.githubusercontent.com/assets/9270388/18719350/e980193e-7fdb-11e6-8747-2515f8dfa0c4.png)

**Comment by needlestack** [comment]
I'm pretty sure the above wouldn't cause any problems.

@spatiald - I noticed the 404 there after the recent server move, I imagine -- I have re-instated that URL.

**Comment by needlestack** [comment]
Don't think this is a problem going forward.
