### ISSUE TITLE
2GB file always arrives corrupted

### ISSUE THREAD

**Issue by bimbayo** [rachelproject/rachelplus#67]
Hi.
I've downloaded the USB image at this [drive](https://drive.google.com/drive/u/0/folders/0ByHHOxPhKBGafkFYTFIzX2M1cmhPcVU1WjhtMWtrN0xvS2MyZnZ4V0Z4MFFJSmVzejNrU00) about six times on different ISPs - each comes corrupted (see unzip error below)

Is there an alternative download location or FTP server somewhere? Another install option?
I'm trying to install RACHEL on a blank Intel CAP device.

I tried the less easy way of 'http://rachel.golearn.us/wiki/mdwiki.html#!rachel-install-CAP.md'. No headway either

Thanks

macbook:Downloads gbas$ unzip RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip 
Archive:  RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip
warning [RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip]:  76 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip]:  reported length of central directory is
  -76 bytes too long (Atari STZip zipfile?  J.H.Holm ZIPSPLIT 1.1
  zipfile?).  Compensating...
   skipping: RACHEL_Recovery_USB_1-2-16_v8_20160707.img  need PK compat. v4.5 (can do v2.1)

note:  didn't find end-of-central-dir signature at end of central dir.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)

**Comment by spatiald** [comment]
The default command line utility in OSX will not work to unzip large files. 

Confirm the MD5 of your downloaded zip file.  Run the following:
`md5 RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip`

You should get:
```
MacBook:rachel$ md5 RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip 
MD5 (RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip) = 305ab7b81c4229b2500e9ed0e4e62ba6
```

Then run the following to unzip the file without installing additional programs:
`tar xzvf RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img.zip`

That should do it.  Re-open if you have additional issues.

**Comment by bimbayo** [comment]
Thanks. Works like a charm. The file downloaded is named RACHEL_Recovery_USB
Is it the same as the Multitool image referred to at https://github.com/rachelproject/rachelplus/wiki/CAP-USB-Recovery-README
USB drive should be formatted as FAT, Ex-FAT or...?
Sorry for the beginner's questions

**Comment by spatiald** [comment]
I need to update the wiki to reflect that the USB multitool is then same as the RACHEL Recovery USB. When imaging a USB with the USB image, you don't have to pre-format the USB as the imaging process images everything on the USB.

**Comment by bimbayo** [comment]
OK Cool. Cos I ran the imaging command and i think its written into the disk but it shows up as blank on Mac - so cant edit .sh to pick the mode of install..

**Comment by needlestack** [comment]
I image on a mac and the USB should be readable and editable -- could you tell me how you're doing the imaging - the exact commands?

**Comment by spatiald** [comment]
Basic steps to image a USB:

- Download image

- Check/verify MD5

- Verify which disk the USB is listed as by running:   ```diskutil list```  In the results below, my attached USB shows as /dev/disk3 (confirm that the drive size matches the USB)...in my case, I have an 8GB hard drive that roughly matches the 7.9GB above.
```
mbpWired:~ sd$ diskutil list
/dev/disk0 (internal, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                        *500.1 GB   disk0
 <---cut out stuff--->
/dev/disk3 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *7.9 GB     disk3
   1:                 DOS_FAT_32 UNTITLED                2.1 GB     disk3s1
   2:                      Linux                         2.3 GB     disk3s2
```

- Run the image command (change out the parts that you need to):  
```
sudo dd if=<path-to>/RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img of=/dev/<your-device-ID> bs=1m
```
Using my output from Step 3, my command would be:  
```
sudo dd if=/Users/<myUser>/Desktop/RACHEL_Recovery_USB_1-2-16_v8_20160707-oldHDschema.img of=/dev/rdisk3 bs=1m
```

- When imaging is complete, check to see if it's mounted.  If not, unplug and reinsert.  If it is, click the eject button and then remove/reinsert your USB.

- Upon inserting the USB, the first partition will mount.  It is a FAT32 partition.  You should be able to modify the update.sh file on that partition.

**Comment by L-Amstutz** [comment]
A little off subject, but may be helpful to someone using Windows.
I found that Windows will not unzip the recent RACHEL_Recovery_USB files even when the MD5 of downloaded ZIP is correct.  I've tried several computers with different versions of Windows (7,8,10), and they all report that there is not enough room on the drive (with over 50GB space available ) to unzip the file --they say they need hundreds of TerraBytes free to unzip!
But I was able to unzip by booting Linux, use CLI "unzip" the iimage.  Then the MD5 of .img checks fine in both linux and Windows, and it can burn to fresh Flash Drive using either Windows "rufus" or linux "dd".

**Comment by spatiald** [comment]
Recently, I spent quite a bit of time testing various iterations of the zip files.  I can't duplicate your issue Leon; although, I feel that I have given it best effort.

HELP WANTED - Is there anyone else with the same issue?  Specifically, you download the compressed zip file of the RACHEL_Recovery_USB, then attempt to extract the .img file to your Windows computer, and then it fails with an error of "not enough space" or similar?

**Comment by L-Amstutz** [comment]
Sam, appreciate your efforts.  Here is a screenshot that show the problem on our Windows 7 office laptops.
[cid:image001.png@01D299AC.15551D90]

**Comment by needlestack** [comment]
I haven't seen this specific problem, but I'll just chime in that I have had occasional problems unzipping files on Windows using the built-in archiver. I have had good luck with [7zip](http://www.7-zip.org/download.html) -- it's free. Leon - care to give it a try and let us know if it works any better for you?

**Comment by L-Amstutz** [comment]
Thanks Jonathan.  You put your finger on the problem - -Window’s ZIP extractor.  I’ve used it for hundreds of other ZIP files but apparently it doesn’t like something about the RACHEL file. I installed 7-ZIP and it successfully extracted the RACHEL Recovery image, unlike the Windows extractor which says it needs Tera or PetaBytes of storage to unzip!
Leon

**Comment by needlestack** [comment]
Awesome! Glad to help.

@spatiald - curious where you zipped it? On the flip side I've had problems when creating archives with the GUI Mac OS archiver ("Compress filename..." in the popup menu). Any chance you used that to create this archive?

**Comment by spatiald** [comment]
I use the createUSB.sh script that is found in the scripts folder of the rachelplus git.  Although I build it to run on OSX and linux, I specifically wanted it to run on the CAP.  

My usually methodology is to insert a rachel recovery usb drive that I want to update into the CAP, download the current createUSB.sh script to /root and run it from there.  

*NOTE* You must be connected to the CAP's wifi when doing this as the CAP will disconnect the wired interface during the USB creation (that is something in the original Gemtek scripts).  

The script will give it approx build times and output feedback during the process.  At the end of the image creation (files are in /media/RACHEL/recovery), it will zip the file using the command ```zip -9 -y -r -q -o $imageName.zip $imageName```.  This is the most Windows friendly zip file that the native zip command will create.  Lastly, it md5 hashes the files and creates a text file for the hashes. 

@needlestack The createUSB.sh script is autonomous after entering a few initial parameters.  I wanted it to do all the dirty work.  After looking at the script, if you can think of a better method for zipping the files, I would be happy to incorporate it.

Current version of createUSB.sh is [here](https://github.com/rachelproject/rachelplus/blob/master/scripts/createUSB.sh)

**Comment by needlestack** [comment]
Hmm, yeah - I would have thought your method would work fine. Not sure why it seems zip files have suddenly become less compatible in the past couple years. Maybe a 32/64 bit thing? My only other guess would be to try updating your command-line zip utility via Homebrew? Or we can just continue recommending 7zip :)

**Comment by j-schwartz** [comment]
I haven't honestly followed the whole thread here, but I downloaded the most recent CAP 1.0 zip file and tried to unzip and got this:

![image](https://cloud.githubusercontent.com/assets/9270388/24333693/80e0dd82-1211-11e7-887d-cdcd9ab8663c.png)

**Comment by j-schwartz** [comment]
I subsequently downloaded and used 7-zip, and received this:
![image](https://cloud.githubusercontent.com/assets/9270388/24333732/30ebf07c-1212-11e7-96c1-757ffeaa1001.png)

**Comment by spatiald** [comment]
Believe this issue is resolved on new recovery builds...on zipping new RACHEL Recovery USB, the [createUSB.sh](https://github.com/rachelproject/rachelplus/blob/master/scripts/createUSB.sh) script now runs the following to build images:
```zip -9 -y -r -q -o $imageName.zip $imageName```
