### ISSUE TITLE
CAP Captive Portal

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#7]
I generally turn the captive portal on the CAP. I had issues particular with phones being able to connect  via Wi-FI with captive portal on.

**Comment by j-schwartz** [comment]
That's disappointing.  This is a big selling feature to me.  Was there any
consistency among brand or phone OS that might have caused the issue?

**Comment by bnordha** [comment]
Mainly my iPhone. Basically it wouldn't connect to the Wi-Fi as it was waiting for the captive portal which never showed up.

We can do some tests on Android to see whether it has some issue.

**Comment by bnordha** [comment]
Did a quick test on IOS Phone and Android phone. Worked ok on Android phone, but not on iPhone.

**Comment by bnordha** [comment]
I found a solution, not sure whether it is the best one though.

Edit the /etc/host file, and add an entry with the IP address of the server, eg.
192.168.88.1    www.rachel.lan rachel.lan

To use the webserver under that address, we also need to add an entry in lighttpd.conf

**Comment by spatiald** [comment]
## What to configure
Working solution follows - only one issue I am working at the moment is that the "button" or link in the captive portal doesn't open a new, full-size browser.

* Copied pass_ticket.shtml and redirect.shtml to /media/RACHEL/rachel (required to maintain user "state" - i.e. know who has already been to the site)

* Modified /usr/local/etc/lighttpd.conf
```
$SERVER["socket"] == ":82" {
	server.document-root = "/media/RACHEL/rachel"
	url.rewrite-once = ( "^(?!/pass_ticket.shtml)" => "/redirect.shtml" )
}
```

* Add this to end of /usr/local/etc/lighttpd.conf
```
# RACHEL
$HTTP["host"] =~ "(^|\.)my\.content$" {
	server.document-root = "/media/RACHEL/rachel"
        url.rewrite-once = ( "^/(.*)" => "/captiveportal-redirect.html" )
}

$SERVER["socket"] == ":80" {
	server.document-root = "/media/RACHEL/rachel"
	index-file.names =("index.php", "index.html", "/_h5ai/server/php/index.php")
  		fastcgi.server = ( ".php" => ((
  			"bin-path" => "/usr/bin/php5-cgi",
  			"socket" => "/tmp/php.socket"
  			)))
}
```

* Added a new file -> /media/RACHEL/rachel/captiveportal-redirect.html
```html
<html>
<head>
</head>
<body link="#000000" vlink="#000000" alink="#377211">
<div style='text-align:center'>
<a href="http://192.168.88.1/index.php" target="_top">
	<img src="http://192.168.88.1/art/rachel_banner.png" />
</a>
<form action="dummyvalue">
<input type="button" value="Click here to enter RACHEL" name="button" onclick="location.href='http://192.168.88.1'" />
</form>
</div>
</body>
```

- - - - -

## HOW IT WORKS:

IPTables takes port 80 and redirects traffic to port 82 (the Captive Portal):
```
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:CAPTIVE - [0:0]
:CAPTIVE_WHITELIST - [0:0]
:CAPTIVE_PASSLIST - [0:0]
-I PREROUTING -i wlan0 -p tcp --dport 80 -j CAPTIVE
-A POSTROUTING -o eth0 -j MASQUERADE
-I CAPTIVE -p tcp -j CAPTIVE_WHITELIST
-I CAPTIVE -p tcp -j CAPTIVE_PASSLIST
-A CAPTIVE -p tcp --dport 80 -j DNAT --to-destination 192.168.88.1:82
-I CAPTIVE_WHITELIST -p tcp -d 192.168.88.1 -j ACCEPT
COMMIT
```

It uses the html files pass_ticket.shtml and redirect.shtml to identify traffic and keep track of previous users so it doesn't keep popping up the box (this is setup in lighttpd.conf).
```html
$SERVER["socket"] == ":82" {
        server.document-root = "/media/RACHEL/rachel"
        url.rewrite-once = ( "^(?!/pass_ticket.shtml)" => "/redirect.shtml" )
}
```

The following code redirects the Captive Portal page to our file captiveportal-redirect.html here:
```html
$HTTP["host"] =~ "(^|\.)my\.content$" {
	server.document-root = "/media/RACHEL/rachel"
        url.rewrite-once = ( "^/(.*)" => "/captiveportal-redirect.html" )
}
```

**Comment by bnordha** [comment]
I had seen two issues with the captive portal.
1) I was not able to connect with my iPhone. It would not get pass the browser on the connection.
2) Sometimes when I want to connect to a website, it would throw me back to the portal even though I am already connected.

Now, mind you that was under the vanilla configuration, which is probably not the most robust implementation.

**Comment by hackersforcharity** [comment]
With our without the setup I proposed?  Other comments inline below.
Sam


On Jul 13, 2015, at 01:12, bnordha <notifications@github.com> wrote:

I had seen two issues with the captive portal.
1) I was not able to connect with my iPhone. It would not get pass the
browser on the connection.

---- I am not sure what you mean by this. The captiveportal-redirect.html
page needs some improvements but should have directed you the RACHEL page.
The captive portal popup can not call the browser (or any executable)
outside of its context; that's a security feature that I don't believe we
can overcome. Hence, you have to close that window and start a new browser
to view full screen.

2) Sometimes when I want to connect to a website, it would throw me back to
the portal even though I am already connected.

---- It throws you back due to the "baked in" dnsmasq settings. When any of
the Intel scripts call for http://my.content, it takes you back to the
portal login page.

---- As an option, we could forget the initial splash page with the button
and have the popup show RACHEL directly. It might be the best solution, the
more I think about it.

Now, mind you that was under the vanilla configuration, which is probably
not the most robust implementation.

—
Reply to this email directly or view it on GitHub
<https://github.com/rachelproject/rachelplus/issues/7#issuecomment-120814383>
.

**Comment by bnordha** [comment]
Actually what is the proposed desired behaviour?

 

The out of the box behaviour (which I do NOT propose) is as follows:

 

1)      Connect SSID ==>Browser pops up to complete successfully SSID association
This is where I have issues with the iPhone

2)      Once SSID is successfully associated (and Internet access is allowed), accessing any external website, e.g. www.google.com <http://www.google.com>  sometimes brings up the portal.

 

 

As you have already noticed, the out of the box configuration/implementation is sometimes “quirky,” I suggest that we define and implement our own desired behaviour and not use any of the defaults as a guide.

 

Cheers, Bernd

**Comment by hackersforcharity** [comment]
Is the out of the box behavior quirky because you changed the default wireless IP to 10.10.10.10?

FWIW, I have a couple iPhones, an iPad, a Macbook and Windows systems. I am running RACHEL on a CAP but use the wireless IP of 192.168.88.1 and have no issues with captive portal.  I believe you are having issues but I wonder if they can sourced to a config change?

**Comment by bnordha** [comment]
The quirky behaviour was with the out of the box configuration, i.e. before
your modifications, I will do so shortly but in the meantime, if it is
working for you, let's consider it closed.

Bernd

**Comment by spatiald** [comment]
Okay...good news on this front.  I attached a screen shot of the latest RACHEL Captive Portal.  It is installed using the post install script:
[Click here for the latest version from GitHub](https://raw.githubusercontent.com/rachelproject/rachelplus/master/cap-rachel-post-install.sh)

Try it out and let me know - you need your IPs to be 192.168.88.1 for now.  Working on a fix for that but not ready for prime time.
![rachel-captive-portal-screenshot](https://cloud.githubusercontent.com/assets/5751915/8762830/aaa09212-2d51-11e5-94b3-97a4b810aecb.png)

**Comment by j-schwartz** [comment]
Looks great.  I'm uploading a couple more very large content modules and
then will give this all a shot.  TED and Radiolab should be up in 20 hours
or so (fingers crossed).

**Comment by bnordha** [comment]
Just tested it.
Ran cap-rachel-post-install.sh, and it went through.

When the captive portal is on, I am getting a 404 error as it tries to access http://my.content 
when I turn the captive portal off, I can access http://192.168.88.1 but not http://my.content

**Comment by spatiald** [comment]
@bnordha and @j-schwartz Can you run the new installer from the main page (copied here as well)?  Let me know if that clears up the captive portal issues you were having.
```bash
wget https://github.com/rachelproject/rachelplus/raw/master/cap-rachel-first-install.sh \
-O /root/cap-rachel-first-install.sh; bash cap-rachel-first-install.sh
```

**Comment by bnordha** [comment]
Yes, it does. It works nicely even with 10.10.10.10.

 

The installation process is working very well now.

**Comment by spatiald** [comment]
Jeremy,
I saw the change to the captive portal page and I agree with it.  However,
we should probably do something to minimize the content to it fits within
the first screen that pops up.  That way, the user doesn't have to scroll
to see our logos.  It isn't bad (only partway cut off) but my ADD is
getting to me :)

**Comment by j-schwartz** [comment]
Will do in ten

**Comment by spatiald** [comment]
@j-schwartz What do you think of this look?  Still says what you added but allows for the logos to be seen in their entirety. 

![image](https://cloud.githubusercontent.com/assets/5751915/8899075/af19ab14-33fd-11e5-92c8-cea4188bdb4c.png)

**Comment by j-schwartz** [comment]
That's great. Thanks Sam

**Comment by spatiald** [comment]
Reopen if needed.

**Comment by bnordha** [comment]
I still the issue on the iPhone at times. Not sure whether it warrants reopening the issue.

When  I connect to the SSID, it t “hangs” at the  Log In screen. See the attached screen shot. There should be a "Done" link, but there is only a "Cancel" Link
![img_3650 1](https://cloud.githubusercontent.com/assets/13216500/9707845/d35d3cac-5545-11e5-99f0-4baab1152154.PNG)

**Comment by spatiald** [comment]
I think this is going to be an ongoing issue…various devices interpret the popup for RACHEL differently.  I have noticed the same random effect on my devices as well.  My thought is to tweak the captive portal to only be presented when the user opens their browser.  This way,  the user can click on the RACHEL banner and be taken to the full RACHEL website.  Would that be a good way to handle the captive portal?

Sam

**Comment by bnordha** [comment]
It is easy to turn the captive portal on and off in the management console, so maybe we should just have it turned off by default.

**Comment by spatiald** [comment]
The effect I think is appropriate is to force an initial webpage redirect
when the user opens their browser.

I don't like a pop up effect that only provides minimal viewing area.

If we do turn it off, we lose the redirect altogether. I'll see about
tweaking the CAP to not popup just force first page redirect.

Thoughts?

Sam



On Sep 8, 2015, at 20:28, bnordha <notifications@github.com> wrote:

It is easy to turn the captive portal on and off in the management console,
so maybe we should just have it turned off by default.

**Comment by spatiald** [comment]
We have a working captive portal.  I am working on a version that will not create a popup but will just redirect the first time someone surfs to a page.  The original issue here is closed, reopen if needed.

**Comment by bnordha** [comment]
Great,

do I just to do option 8,8 to install that feature?

Bernd

**Comment by spatiald** [comment]
The option numbers changed when i recently added an item.  But it would be the "repair firmware" option to check your captive portal setup is correct.  No harm will come from running that script.
