### ISSUE TITLE
How to reset and start from scratch

### ISSUE THREAD

**Issue by click2tman** [rachelproject/rachelplus#70]
I purchased the Rachelplus over a year ago but due to whatever reason, I think its messed up. I want to start from scratch. Delete everything on it and install a new copy just like it came when I purchased it.

**Comment by spatiald** [comment]
You probably want to save the content on your hard drive. If so, download the v8 USB:
https://drive.google.com/open?id=0ByHHOxPhKBGaT3A4YWR3MUVtOGc

Follow the instructions here to burn the image to a USB:
http://rachel.golearn.us/wiki/mdwiki.html#!cap-usb-recovery.md

When complete, insert the USB into the CAP with the CAP off. Start the USB and wait for the imaging to complete. The LED codes will tell when they are complete, as noted here:
http://rachel.golearn.us/wiki/mdwiki.html#!cap-usb-recovery.md

When complete, press the on/off button, wait for the CAP to shut down, and then start the CAP. It will start up and run for a couple mins while it completes a few install scripts. When completely finished it will shut down.  That's it...all done. Start the CAP and it should be working and back in an updated state.

**Comment by spatiald** [comment]
I'll write up a formal wiki post on how to do this for both old and new hard drive schema's.

**Comment by j-schwartz** [comment]
I tried running the script, and I feel like I'm stuck in a re-partitioning loop.  

> RACHEL CAP Configuration Script - Version 20161227.1105
[+] Started:  Wed Jan 11 20:20:25 EST 2017
[+] Log directory:  /var/log/rachel
[+] Temporary file directory:  /root/cap-rachel-install.tmp
[+] Ubuntu 12.04.3 LTS i686 Detected.

[?] Do you want to run in ONLINE (a network location) or OFFLINE (USB drive) mode?
1) ONLINE
2) OFFLINE
#? 1

[+] Script set for 'ONLINE' mode.

[+] Internet connection confirmed...continuing install.

[+] RACHEL CAP Configuration Script - Version 20161227.1105
[+] Script started: Wed Jan 11 20:20:26 EST 2017

[*] Conducting a new install of RACHEL on a CAP.

[*] Directory of RACHEL install log files with date/time stamps:
/var/log/rachel

[-] WARNING:  This will completely wipe your CAP and restore to RACHEL defaults.
Any downloaded modules WILL be erased during this process.

Are you ready to start the install? (y/N) y

[*] Locations for downloading packages:
    US) United States
    UK) United Kingdom
    SG) Singapore
    CN) China (CAP Manufacturer's Site)

[?] For the package downloads, select the location nearest you? 
1) US
2) UK
3) SG
4) CN
#? 1

[*] Downloading packages from the United States.
WARNING: combining -O with -r or -p will mean that all downloaded content
will be placed in the single file you specified.

--2017-01-11 20:20:29--  https://raw.githubusercontent.com/rachelproject/rachelplus/master/sources.list/precise/sources-us.list
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 547 [text/plain]
Saving to: `/etc/apt/sources.list'

     0K                                                       100% 54.0M=0s

2017-01-11 20:20:29 (54.0 MB/s) - `/etc/apt/sources.list' saved [547/547]

FINISHED --2017-01-11 20:20:29--
Total wall clock time: 0.1s
Downloaded: 1 files, 547 in 0s (54.0 MB/s)
[+] Command successful.

[*] Downloading RACHEL install scripts for CAP to the temp folder /root/cap-rachel-install.tmp.

[*] Downloading cap-rachel-first-install-2.sh
WARNING: combining -O with -r or -p will mean that all downloaded content
will be placed in the single file you specified.

--2017-01-11 20:20:29--  https://raw.githubusercontent.com/rachelproject/rachelplus/master/install/cap-rachel-first-install-2.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1696 (1.7K) [text/plain]
Saving to: `cap-rachel-first-install-2.sh'

     0K .                                                     100%  109M=0s

2017-01-11 20:20:29 (109 MB/s) - `cap-rachel-first-install-2.sh' saved [1696/1696]

FINISHED --2017-01-11 20:20:29--
Total wall clock time: 0.2s
Downloaded: 1 files, 1.7K in 0s (109 MB/s)
[+] Command successful.

[*] Downloading cap-rachel-first-install-3.sh
WARNING: combining -O with -r or -p will mean that all downloaded content
will be placed in the single file you specified.

--2017-01-11 20:20:29--  https://raw.githubusercontent.com/rachelproject/rachelplus/master/install/cap-rachel-first-install-3.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.128.133, 151.101.64.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4780 (4.7K) [text/plain]
Saving to: `cap-rachel-first-install-3.sh'

     0K ....                                                  100% 1.13M=0.004s

2017-01-11 20:20:30 (1.13 MB/s) - `cap-rachel-first-install-3.sh' saved [4780/4780]

FINISHED --2017-01-11 20:20:30--
Total wall clock time: 0.2s
Downloaded: 1 files, 4.7K in 0.004s (1.13 MB/s)
[+] Command successful.

[*] Delete previous RACHEL setup commands from /root/rachel-scripts/rachelStartup.sh
[+] Done.

[*] Starting first install script...please wait patiently (about 30 secs) for first reboot.
[*] The entire script (with reboots) takes 2-5 minutes.

[*] Backup current partition table to /root/rachel-scripts/gpt.backup
The operation has completed successfully.

[*] Unmounting any mounted partitions.

[*] Repartitioning hard drive
Disk /dev/sda: 976773168 sectors, 465.8 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): E24F7B1A-4238-431F-AB83-759C42A1F0C1
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 976773134
Partitions will be aligned on 2048-sector boundaries
Total free space is 4062 sectors (2.0 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         6293503   3.0 GiB     8300  preloaded
   2         6293504        41945087   17.0 GiB    8300  uploaded
   3        41945088       976771086   445.8 GiB   8300  RACHEL
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot.
The operation has completed successfully.
Error: Partition(s) on /dev/sda are being used.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot.
The operation has completed successfully.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot.
The operation has completed successfully.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot.
The operation has completed successfully.
Disk /dev/sda: 976773168 sectors, 465.8 GiB
Logical sector size: 512 bytes
Disk identifier (GUID): 87F9902D-F468-4A9C-96C9-257391FDD81F
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 976773134
Partitions will be aligned on 2048-sector boundaries
Total free space is 4062 sectors (2.0 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048         6293503   3.0 GiB     8300  preloaded
   2         6293504        41945087   17.0 GiB    8300  uploaded
   3        41945088       976771086   445.8 GiB   8300  RACHEL
[+] Done.

[*] Adding /dev/sda partitions into /etc/fstab
[+] Done.

[+] RACHEL CAP Install - Script 1 of 3 ended at Wed Jan 11 20:20:35 EST 2017

[*] I need to reboot; once rebooted, please run the next download/install command.
[*] Rebooting in 5 seconds...
root@WRTD-303N-Server:~# 
Broadcast message from root@WRTD-303N-Server
        (/dev/pts/0) at 20:20 ...

The system is going down for reboot NOW!

>

**Comment by spatiald** [comment]
@j-schwartz The previous comment you made on this issue doesn't seem to flow with the OP's original issue.  Can you clarify?  Are you speaking to the initial install function of the configure script?  If so, that was built specifically to solve the initial issue we had years ago of building up a raw CAP (without RACHEL) into a RACHEL-Plus (without using the RACHEL-Recovery-USB.  

For the OP's issue, using the RACHEL-Recovery-USB is there best option.

**Comment by spatiald** [comment]
While this issue is rather old...I updated [my developer wiki](http://rachel.golearn.us/wiki/mdwiki.html#!index.md) to include a bunch of info on RACHEL and, to the OP, I add posts on how to install RACHEL, build a RACHEL Recovery USB, updating content, and more.
