### ISSUE TITLE
ExFAT (or something)

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelplus#71]
Right now if you wanted to update a Plus using a USB HD, the only common file system between Windows/Mac and Linux is FAT... and that can't hold the larger kiwix index files like `wikipedia_en_all_2016-02.zim.idx/postlist.DB`. If we had ExFAT support, we could install content directly from a USB HD.

**Comment by needlestack** [comment]
If it's any help the three modules you need to install are:

    fuse-utils_2.8.6-2ubuntu2.1_all.deb
    fuse-exfat_1.0.1-1_i386.deb
    exfat-utils_1.0.1-1_i386.deb

I copied these three to `rachel-files/offlinepkgs` and added them to the end of `debPackageList` in `cap-rachel-configure.sh`. It worked as expected with one strange effect: when the CAP first started after running the USB (method 3) it did a `halt` instead of `restart` and required a second button-push to bring it back up. Just FYI :)

**Comment by spatiald** [comment]
Geez...sorry for the confusion.  Moved this to Milestone 9.1.1
