### ISSUE TITLE
ka-lite multi-language api

### ISSUE THREAD

**Issue by needlestack** [rachelproject/rachelplus#72]
Can we have the USB apply the kalite language patch as part of the update process? We should apply that patch in all cases as it doesn't disrupt anything else but is required for the latest kalite modules that allow for multi-language hosting...

**Comment by needlestack** [comment]
I'm also going to see if I can get this addition into the kalite mainline so we don't need to worry about it in the future. No idea if they'll go for that, though!

**Comment by needlestack** [comment]
Hey cool - the ka-lite folks [accepted and merged my patch](https://github.com/learningequality/ka-lite/pull/5342)! We still need this change to cover us until their next release (undetermined) but it's part of the ka-lite development branch now. Yay for open source!

**Comment by benjaoming** [comment]
Our next release 0.17 will be before '17 starts, we don't wanna end up in a situation where people think our release number is aligned with the year :)

**Comment by spatiald** [comment]
May we should wait on 0.17 to publish before releasing the new USB?  What do you think @needlestack ?

**Comment by needlestack** [comment]
Yep, if it's coming in the next month, that sounds good to me!

**Comment by spatiald** [comment]
Manual fix as posted by @needlestack:

You would need to [download this file](https://raw.githubusercontent.com/rachelproject/rachelplus/master/scripts/KALITE-MULTILINGUAL-api_views.py) and save it on that RACHEL-Plus as /usr/lib/python2.7/dist-packages/kalite/i18n/api_views.py, and then run kalite restart. This can be done through ssh if you can physically get to the RACHEL with a laptop and that file.

Added to v9.1.1 milestone
