### ISSUE TITLE
Where to get the content for USB stick

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#8]
Line 73 of the current install script calls for the content to be put on the USB stick. Where can I get that content?

**Comment by j-schwartz** [comment]
Right now, the content package is a bit of a mish mash.

My external harddrive has four sub folders and sphider_plus.sql:
[image: cap.PNG]
kacontent includes a khan subfolder and all the videos for KA-lite.  We
have resized all the khan videos from the latest release of KA-lite.  These
are available at http://rachelfriends.org/z-holding/ka-lite_content.zip

logos is a set of RACHEL logos I resized.  I haven't loaded these
anywhere.  I will put them on GitHub tomorrow

otherkalite is the assessmentitems.json which for me, was not natively
downloading from ka-lite during install.  hopefully you don't need this.  I
talked to jamie at learning equality today.  They're releasing v0.14 next
week.

The last folder is rachel.  Most of this framework can be taken from a
rachelusb_32EN_3.1.5.zip download (again from
rachelfriends.org/rachelusb_32EN/ )

[image: rachel.PNG]

I deleted some unneeded folders.

Also, within modules, I have added TED, GCF, PhET, and radiolab.

Those are available on dev.worldpossible.org/mods - but I need to get
Jonathan Field (cc'd) to refresh the page there that actually shows the
modules.

sphider_plus will also be on the mods site soon.

**Comment by edresor** [comment]
Jeremy,
Thanks.  It's great you guys are able to keep up with the new KA-Lite videos.  You never know when helping some kid with SAT Prep is going to move things forward at a faster rate.

SAT Prep in East Africa can be quite expensive, just like in Manhattan.  In fact one private Christian school in Nairobi advertises using a Manhattan prep company over spring break, probably at a significant extra cost to families.  You remember, "pay unto Caesar what is Caesar's"
Ed

**Comment by spatiald** [comment]
Content now available via two methods:
1. Download to computer via http://dev.worldpossible.org/mods

2. Download directly to CAP via configure script (interactive mode, option 6 or 7)
