### ISSUE TITLE
eMMC vs HDD Storage

### ISSUE THREAD

**Issue by bnordha** [rachelproject/rachelplus#9]
The CAP has two storages, an 8GB eMMC and a 500GB standard 2.5" HDD. The eMMC storage is where the OS sits. The HDD in generally contains content. The CAP can operate without the HDD. 

I would recommend to put as much on the HDD as possible. When I was configuring CAP units, I made a master copy, and then cloned the HDD by physically pulling the HDD out of the chassis and cloning it with CloneZilla on a desktop.

Then I only had to made some minor modifications on the eMMC storage.

I haven't use the MPT (Mass Provisioning Tool) as it wasn't quite ready for prime time by the time I left Intel.

Thoughts?

**Comment by spatiald** [comment]
Moved the first paragraph to the wiki...closing.
